// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvgijj7SlgxXzkheoijz6TTs5YLUeBazA',
    appId: '1:1042627834115:web:650411ff87e05dfd277936',
    messagingSenderId: '1042627834115',
    projectId: 'hello1-bc71d',
    authDomain: 'hello1-bc71d.firebaseapp.com',
    storageBucket: 'hello1-bc71d.firebasestorage.app',
    measurementId: 'G-R0FWR6V4W9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBL1eTNgWsuCU8srP298HvIfpHPiPDSyg8',
    appId: '1:1042627834115:android:7fcfac78ca2957e4277936',
    messagingSenderId: '1042627834115',
    projectId: 'hello1-bc71d',
    storageBucket: 'hello1-bc71d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdc1Uo8IOgypq-7BvfN6r71gu-Nil-QWg',
    appId: '1:1042627834115:ios:662aca0bbf05a35d277936',
    messagingSenderId: '1042627834115',
    projectId: 'hello1-bc71d',
    storageBucket: 'hello1-bc71d.firebasestorage.app',
    iosBundleId: 'com.example.activity01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdc1Uo8IOgypq-7BvfN6r71gu-Nil-QWg',
    appId: '1:1042627834115:ios:662aca0bbf05a35d277936',
    messagingSenderId: '1042627834115',
    projectId: 'hello1-bc71d',
    storageBucket: 'hello1-bc71d.firebasestorage.app',
    iosBundleId: 'com.example.activity01',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvgijj7SlgxXzkheoijz6TTs5YLUeBazA',
    appId: '1:1042627834115:web:3ae0674307a693b1277936',
    messagingSenderId: '1042627834115',
    projectId: 'hello1-bc71d',
    authDomain: 'hello1-bc71d.firebaseapp.com',
    storageBucket: 'hello1-bc71d.firebasestorage.app',
    measurementId: 'G-XR7016Y66D',
  );
}
